### PR TITLE
Add linux aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel build support.
Related to #29. @zhuyifei1999, could you please review this PR?

### CODE REVIEW

**Comment by zhuyifei1999** [comment]
Is `dist: focal` required?

Should I test if cibuildwheel works as expected on aarch64? Otherwise I could let it run as part of next release (I'm planning to do it when I fix #27, or when Python 3.10 comes out, whichever comes earlier, but if you want I can release immediately).

**Comment by odidev** [comment]
> Is `dist: focal` required?

`dist: focal`  is not mandatory, we can remove it, by default it will be Xenial. Please let me know if you want me to remove it.

> Should I test if cibuildwheel works as expected on aarch64? Otherwise I could let it run as part of next release (I'm planning to do it when I fix #27, or when Python 3.10 comes out, whichever comes earlier, but if you want I can release immediately).

If I am understanding, your concern is that whether cibuildwheel supports aarch64 or not. If yes, then there is no need to test it, cibuildwheel is supported for aarch64.
Please let me know if you have any other concerns.
It would be really helpful if you release the wheels in your next release.

**Comment by zhuyifei1999** [comment]
> `dist: focal` is not mandatory, we can remove it, by default it will be Xenial. Please let me know if you want me to remove it.

cibuildwheel: 

As I understand, cibuildwheel starts a docker container, which will have a full root filesystem inside, right? Therefore, the choice of the distro version should not matter, as long as they support docker, right?

If that is the case, I prefer to have the least amount of time-dependent configs as possible, since I would then be responsible for updating them when it fails to work one day when focal is EOL.

test builds:

I would prefer default xenial, one to keep consistent with x86_64 test builds, two, similar to cibuildwheel, for less maintenance.

Do you want me to release immediately after merge?

**Comment by odidev** [comment]
> > `dist: focal` is not mandatory, we can remove it, by default it will be Xenial. Please let me know if you want me to remove it.
> 
> cibuildwheel:
> 
> As I understand, cibuildwheel starts a docker container, which will have a full root filesystem inside, right? Therefore, the choice of the distro version should not matter, as long as they support docker, right?
> 
> If that is the case, I prefer to have the least amount of time-dependent configs as possible, since I would then be responsible for updating them when it fails to work one day when focal is EOL.
> 
> test builds:
> 
> I would prefer default xenial, one to keep consistent with x86_64 test builds, two, similar to cibuildwheel, for less maintenance.
> 
> Do you want me to release immediately after merge?

I have removed focal distro as discussed and it would be really helpful if you can release it after the merge.

**Comment by zhuyifei1999** [comment]
ok I'll do a release rn

**Pull request merged**
